name: gradlew

on:
  push:
    branches:
      - workflow

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: SimonMarquis/ci-gradle-properties-action@v1
        with:
          path: .github/gradle.properties
      - run: java --version
      - run: gradle -v
